services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /llm-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures live-reloading works inside Docker

